;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="Keys.RedKey",NewTagName="Keys.Red Key")
+GameplayTagRedirects=(OldTagName="Keys.Blue Key",NewTagName="Keys.Cyan Key")
+GameplayTagRedirects=(OldTagName="Keys.Red Key",NewTagName="Keys.Yellow Key")
+GameplayTagList=(Tag="BlueKey",DevComment="")
+GameplayTagList=(Tag="Items",DevComment="")
+GameplayTagList=(Tag="Items.Blue Gem",DevComment="")
+GameplayTagList=(Tag="Items.Green Gem",DevComment="")
+GameplayTagList=(Tag="Items.Red Gem",DevComment="")
+GameplayTagList=(Tag="Keys",DevComment="")
+GameplayTagList=(Tag="Keys.Cyan Key",DevComment="")
+GameplayTagList=(Tag="Keys.Purple Key",DevComment="")
+GameplayTagList=(Tag="Keys.Yellow Key",DevComment="")
+GameplayTagList=(Tag="OrangeKey",DevComment="")
+GameplayTagList=(Tag="PurpleKey",DevComment="")
+GameplayTagList=(Tag="RedKey",DevComment="")
+GameplayTagList=(Tag="TestKey",DevComment="")
+GameplayTagList=(Tag="YellowKey",DevComment="")

