;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="Keys.RedKey",NewTagName="Keys.Red Key")
+GameplayTagRedirects=(OldTagName="Keys.Blue Key",NewTagName="Keys.Cyan Key")
+GameplayTagRedirects=(OldTagName="Keys.Red Key",NewTagName="Keys.Yellow Key")
+GameplayTagRedirects=(OldTagName="Keys.Chapel",NewTagName="Keys.Chapel Key")
+GameplayTagList=(Tag="BlueKey",DevComment="")
+GameplayTagList=(Tag="Items",DevComment="")
+GameplayTagList=(Tag="Items.Blue Gem",DevComment="")
+GameplayTagList=(Tag="Items.Green Gem",DevComment="")
+GameplayTagList=(Tag="Items.Red Gem",DevComment="")
+GameplayTagList=(Tag="Items.Symbol",DevComment="")
+GameplayTagList=(Tag="Keys",DevComment="")
+GameplayTagList=(Tag="Keys.A1Key",DevComment="")
+GameplayTagList=(Tag="Keys.Chapel Key",DevComment="")
+GameplayTagList=(Tag="Keys.Cyan Key",DevComment="")
+GameplayTagList=(Tag="Keys.East Staircase Key",DevComment="")
+GameplayTagList=(Tag="Keys.Library Key",DevComment="")
+GameplayTagList=(Tag="Keys.Moon Key",DevComment="")
+GameplayTagList=(Tag="Keys.Purple Key",DevComment="")
+GameplayTagList=(Tag="Keys.Star Key",DevComment="")
+GameplayTagList=(Tag="Keys.Sun Key",DevComment="")
+GameplayTagList=(Tag="Keys.West Staircase Key",DevComment="")
+GameplayTagList=(Tag="Keys.Yellow Key",DevComment="")
+GameplayTagList=(Tag="OrangeKey",DevComment="")
+GameplayTagList=(Tag="PurpleKey",DevComment="")
+GameplayTagList=(Tag="RedKey",DevComment="")
+GameplayTagList=(Tag="ShadowPuzzelKey",DevComment="")
+GameplayTagList=(Tag="TestKey",DevComment="")
+GameplayTagList=(Tag="YellowKey",DevComment="")

